---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: dev1
      namespace: dev1-ns
    rules:
      - apiGroups:
          - policy
        resourceNames:
          - pks-restricted
        resources:
          - podsecuritypolicies
        verbs:
          - use
kind: List
---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: dev1
      namespace: dev1-ns
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: dev1
    subjects:
      - kind: ServiceAccount
        name: dev1
kind: List
